name: Linting & code analysis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.2.*"]
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        env:
          POETRY_VERSION: ${{ matrix.poetry-version }}
        run: pipx install poetry==$POETRY_VERSION

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          poetry env use $PYTHON_VERSION
          poetry install

      - name: Run linting analysis
        run: |
          poetry run pflake8 mcmng
          poetry run mypy mcmng
          poetry run pylint mcmng
          poetry run black --check mcmng
